spring:
  h2:
    console:
      enabled: true
  datasource:
     driver-class-name: org.h2.Driver
     url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
     username: sa
     password: 1234
     #driverClassName: org.mariadb.jdbc.Driver
     #url: jdbc:mariadb://14.47.229.122:3306/onebody_project?characterEncoding=UTF-8&serverTimezone=UTC
     #username: telf
     #password: telefield@1
     hikari:
       maximum-pool-size: 100
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: update

server:
  port: 9443

logging:
  level:
    org.hibernate: info


mqtt:
  MQTT_USERNAME: telefield
  MQTT_PASSWORD: telefield@1
  BROKER_URL: tcp://localhost:1883
